name: fix_master
description: "A comprehensive mobile application for smartphone repair, hardware diagnostics, and maintenance management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.7.1
  equatable: ^2.1.0
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  path_provider: ^2.1.6
  intl: ^0.20.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  isar_community_generator: ^3.3.2
  build_runner: ^2.15.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/fix_master_image.jpg
    - assets/sounds/startup_sound.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fix_master_image.jpg"
  adaptive_icon_background: "#E3EEF2"

flutter_native_splash:
  color: "#E3EEF2"
  image: assets/images/fix_master_image.jpg
  fullscreen: true
  android_12:
    image: assets/images/fix_master_image.jpg
    icon_background_color: "#E3EEF2"